[package]
name = "trangam"
version = "0.1.0"
authors = ["PiyushXCoder <piyush.raj.kit@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libmath = "0.2.1"
serialport = "4.0.0"
gtk = "0.9.2"
gio = "0.9.1"
glib = "0.10.3"
png = "0.16.8"
cairo-rs = { version = "0.9.1", features = ["png"] }
rand = "0.8.0"
